# Generated by Django 3.0 on 2020-03-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_archives_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='logo_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='archives',
            name='num_of_days',
            field=models.IntegerField(default=1),
        ),
    ]
