# Generated by Django 3.0 on 2020-03-12 19:20

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200201_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=authentication.models.EmailField(max_length=254, unique=True),
        ),
    ]
